springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix:
      file-date-format:

spring:
  profiles:
    include: ${ENV:local}